-- pg_otel_tracer--0.1.0.sql
-- OpenTelemetry tracing extension for PostgreSQL

-- complain if script is sourced in psql, rather than via CREATE EXTENSION
\echo Use "CREATE EXTENSION pg_otel_tracer" to load this file. \quit

-- This extension is primarily C-based. SQL wrappers are auto-generated by pgrx
-- from #[pg_extern] functions in src/lib.rs.
